action update

diff --git a/.github/workflows/packer-test.yml b/.github/workflows/packer-test.yml
--- a/.github/workflows/packer-test.yml
+++ b/.github/workflows/packer-test.yml
@@ -37,16 +37,16 @@ jobs:
         run: |
           packer init ./packer/ami.pkr.hcl
 
-      - name: Run packer fmt
-        run: |
-          if ! packer fmt -check ./packer/ami.pkr.hcl; then
-          echo "Failed - Packer fmt"
-          exit 1
-          fi
-
       - name: Run packer validate
         run: |
           if ! packer validate -evaluate-datasources --var-file=./packer/ami.pkvars.hcl ./packer/ami.pkr.hcl; then
           echo "Failed - Packer validate"
+          exit 1
+          fi
+          
+      - name: Run packer fmt
+        run: |
+          if ! packer fmt -check ./packer/ami.pkr.hcl; then
+          echo "Failed - Packer fmt"
           exit 1
           fi
